发行日期 = ""
出品 = []
前缀 = ""
中文名 = "你的灵魂长出一枝玫瑰"
英文名 = ""
后缀 = "言和版"
歌词制作 = ["SST"]
发布 = ""
购买 = ""
电子 = ""
演唱 = ["言和"]
作词 = ["瞳荧"]
作曲 = ["CFMing", "苗茁", "瞳荧", "小沫", "斯大王", "西门振", "泠泠"]
编曲 = ["CFMing", "苗茁", "斯大王", "西门振", "泠泠"]
调校 = ["纳兰寻风"]
曲绘 = []
混音 = ["CFMing"]
