发行日期 = "2026-04-29"
出品 = ["TOPKINGCREAM"]
前缀 = ""
中文名 = ""
英文名 = "metaphorical girl"
后缀 = "Re"
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Hn9xBVEtZ)"
购买 = ""
电子 = ""
演唱 = []
作词 = ["TOPKINGCREAM"]
作曲 = ["TOPKINGCREAM"]
编曲 = ["TOPKINGCREAM"]
调校 = ["TOPKINGCREAM"]
曲绘 = []
混音 = ["TOPKINGCREAM"]
