发行日期 = "2026-03-20"
出品 = []
前缀 = ""
中文名 = "光年回响"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1ejAjz4Ena)"
购买 = ""
电子 = ""
演唱 = []
作词 = ["Kevinz", "雒清辞明", "CrClr", "果汁凉菜", "薛钦", "空气凝"]
作曲 = ["1-Zero", "空气凝"]
编曲 = ["1-Zero"]
调校 = []
曲绘 = []
混音 = ["Wovop", "CrClr", "欧Ωhm", "棕色环", "阿耗", "Eden / 咖喱"]
