发行日期 = ""
出品 = ""
歌词制作 = ""
发布 = ""
购买 = ""
电子 = ""
演唱 = ["言和"]
作词 = ["大九_LN"]
作曲 = ["lbg", "辻原一郎", "雪人Snowman", "星辉p", "litterzy"]
编曲 = []
调校 = ["瑞安Ryan不跑调", "某只泽", "陌生来访", "litterzy"]
曲绘 = ["多尔及利亚"]
混音 = []
