发行日期 = "2020-11-06"
出品 = "平行四界Quadimension"
歌词制作 = "虎啸ROAR"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1ND4y1R7fB/)"
购买 = "[淘宝 平行四界Quadimension](http://t.cn/A6GtIEhX) ￥75/￥110/￥150/￥200"
电子 = "随专辑附赠"
演唱 = ["星尘", "海伊", "诗岸"]
作词 = ["Ddickky", "大♂古", "芍杳", "大九_LN", "绿无", "杏花包子", "Zeno"]
作曲 = ["Kide", "papaw泡泡", "Evalia", "星辉P", "公兔", "磁带君", "MeLo", "PoKeR", "Zeno"]
编曲 = ["Kide", "papaw泡泡", "Evalia", "星辉P", "公兔", "磁带君", "MeLo", "PoKeR", "Zeno"]
调校 = ["瑞安Ryan", "折v", "奶油蘑菇", "坐标P"]
曲绘 = ["大汉Jax", "November", "Hanasa", "原子Dan", "匙", "影依望远镜", "Leiq雷", "-REDUM-", "青梅丨plumw"]
混音 = ["公兔", "哈密瓜"]
