发行日期 = "2016-12-04"
出品 = []
前缀 = ""
中文名 = "茜色诗集"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Ys411r7T4/)"
购买 = ""
电子 = "[Dizzylab](https://www.dizzylab.net/d/akanepoems/) ￥25"
演唱 = ["泠鸢yousa"]
作词 = ["king", "泠鸢yousa", "曦行；谢阿风", "冥凰"]
作曲 = ["盖盖", "泠鸢yousa", "怪盗V", "wing翼", "玖玲", "西门振", "小野道"]
编曲 = ["盖盖", "Wing翼", "Leon", "wing翼", "玖玲", "西门振", "小野道"]
调校 = []
曲绘 = ["云间蓝", "Bison仓鼠", "四木夕雨", "瑠", "红鸦", "星垣", "抹茶"]
混音 = ["CuTTleFiSh", "盖盖", "小野道"]
