发行日期 = "2017-10-01"
出品 = "Zeno"
购买 = "[专辑购买](http://t.cn/R0nFwnV)"
演唱 = ["星尘"]
作词 = ["Zeno"]
作曲 = ["Zeno"]
调校 = ["Zeno"]
作品类型 = "原创曲"
编曲混音 = ["Zeno"]
曲绘 = ["匙"]
PV = ["CrizCzy"]
简介 = "Zeno个人专辑『Freesia』feat. 星尘试听PV 专辑购买：http://t.cn/R0nFwnV STAFF见片尾 感谢大家的支持和为这张专辑辛苦付出的各位✡"
