发行日期 = "2017-10-01"
出品 = "Zeno"
歌词制作 = "九九Lrc歌词网～www.99Lrc.com"
发布 = ""
购买 = "[专辑购买](http://t.cn/R0nFwnV)"
电子 = ""
演唱 = ["星尘"]
作词 = ["Zeno"]
作曲 = ["Zeno"]
编曲 = ["Zeno"]
调校 = ["Zeno"]
曲绘 = ["匙"]
混音 = []
