发行日期 = "2025-09-11"
出品 = []
前缀 = ""
中文名 = "星-城"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1JHH9zWEUC)"
购买 = ""
电子 = ""
演唱 = ["星尘"]
作词 = ["鱼丸面/凌墨"]
作曲 = ["心焱/亚克Ark"]
编曲 = ["心焱"]
调校 = ["诗书济世长"]
曲绘 = ["Eurekasuki/鱼丸面"]
混音 = ["心焱", "Biapia", "山茫", "清风 Sunny"]
母带 = []
视频 = []
策划 = []
