发行日期 = "2020-04-23"
出品 = ["梗梗", "夜屠灵"]
前缀 = ""
中文名 = "海盼伊人"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1xg4y1z7HL/)"
购买 = "通贩不可用"
电子 = "随专辑附赠"
演唱 = ["海伊", "赤羽", "花筝Anly", "星尘"]
作词 = ["亦晗", "青士", "素珏", "砂妍Lumean", "安筱然", "离南", "水螅", "LSun"]
作曲 = ["夜屠灵", "一只冥河随母", "Teddy-Tian", "七简", "涅不拉几的", "阿原Adam"]
编曲 = ["Cyo", "一只冥河随母", "Teddy-Tian", "夜屠灵", "紫血崎", "七简", "comet音乐工作室", "涅不拉几的", "阿原Adam"]
调校 = ["白漪风铃", "瑞安Ryan", "璟轩", "天雨清明", "风继阳", "星葵", "梨梨夜", "不安定", "桂月锁心", "溱绫西陌"]
曲绘 = ["墨石星", "佐助", "Aubefleurs", "萱草", "砚曲", "LovuAshyL", "唐兰", "言玖", "gx君", "若子", "蚀中Tick", "洋芋"]
混音 = ["一只冥河随母", "Teddy-Tian", "夜屠灵", "七简", "栗子", "不安定"]
