发行日期 = "2018-11-10"
出品 = ["我是石榴皮"]
前缀 = ""
中文名 = "雨中巴士站"
英文名 = ""
后缀 = ""
歌词制作 = ["RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1it411m7yJ/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/YZBSZ/) ￥20"
演唱 = ["星尘"]
作词 = ["46"]
作曲 = ["46"]
编曲 = ["46"]
调校 = ["46"]
曲绘 = ["Pa"]
混音 = ["46"]
