发行日期 = "2020-09-01"
出品 = ["萱草"]
歌词制作 = ""
发布 = "[Bilibili](https://www.bilibili.com/video/BV1EA411n762/)"
购买 = "通贩不可用"
电子 = "随专辑附赠"
演唱 = ["赤羽", "星尘", "心华", "诗岸"]
作词 = ["亦晗", "夜屠灵", "安筱然", "冰心雪蕊", "何雷"]
作曲 = ["夜屠灵"]
编曲 = ["夜屠灵"]
调校 = ["夜屠灵", "天雨清明", "棉花P", "桂月锁心", "TC德"]
曲绘 = ["Achie", "阿凉", "萱草", "蚀中Tick", "枸杞叶", "AIR", "西禾是酥酥"]
混音 = []
