发行日期 = "2021-12-03"
出品 = "['奶牛组']"
歌词制作 = "['RQvan']"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1XU4y1T7yA/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/MIYU0101/) ￥79"
演唱 = ["星尘", "赤羽", "海伊", "诗岸", "牧心"]
作词 = ["沈病娇", "大九_LN", "Evalia"]
作曲 = ["Evalia"]
编曲 = ["Evalia"]
调校 = ["佑可猫", "陌生来访", "Evalia"]
曲绘 = ["Lio"]
混音 = ["Evalia"]
