发行日期 = "2016-07-04"
出品 = ["霾Axis"]
前缀 = ""
中文名 = ""
英文名 = "Dear"
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV19s411v7vS)"
购买 = ""
电子 = ""
演唱 = ["洛天依", "言和", "乐正绫", "星尘"]
作词 = ["雨狸"]
作曲 = ["玖玲", "Litterzy", "崩坏", "DELA_P", "兄贵大乱斗", "DELA/雨狸"]
编曲 = ["玖铃"]
调校 = ["颗粒", "花儿不哭"]
曲绘 = ["鲜洋芋土豆马铃薯", "YAL", "莱勒", "闻香Nadir", "β"]
混音 = ["POiSON"]
