发行日期 = ""
出品 = []
前缀 = ""
中文名 = "夏浪派对"
英文名 = ""
后缀 = "2025"
歌词制作 = []
发布 = ""
购买 = ""
电子 = ""
演唱 = ["乐正绫 乐正绫粉丝", "洛天依", "乐正绫"]
作词 = ["林檎desu", "林檎", "北山薇", "举烛/烦躁月亮饼干"]
作曲 = ["空想纪录", "售货机计划 Vending Machine Project/Elders", "Exci-Ted (VMP)", "寒困困", "半只金蓝", "轻水/烦躁月亮饼干"]
编曲 = ["空想纪录", "售货机计划 Vending Machine Project/空想", "空想 (VMP)", "怀归 (VMP)", "半只金蓝", "轻水"]
调校 = ["水母", "血焰玖蝶 磷元素P", "跨海星尘", "Creuzer"]
曲绘 = ["蛤蜊", "半只金蓝", "syknot", "白"]
混音 = ["DJ鱼谷", "蓝欣也是蓝斤欠"]
