"发行日期" = "2025-05-22"
"出品" = []
"前缀" = ""
"中文名" = "夏日应时而至"
"英文名" = ""
"后缀" = "彩胶版"
"歌词制作" = ["SST"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1XkJpzDEX7)"
"购买" = ""
"电子" = ""
"演唱" = []
"作词" = ["iKz", "邪叫教主"]
"作曲" = ["iKz", "西门振", "海鲜面"]
"编曲" = ["iKz", "西门振", "海鲜面"]
"调校" = []
"曲绘" = []
"混音" = []
"母带" = []
"视频" = []
"策划" = []
