发行日期 = "2023-11-08"
出品 = ["忘川风华录"]
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1c84y1X7KZ/)"
购买 = "通贩不可用"
电子 = "电子版不可用"
演唱 = ["苍穹", "赤羽", "海伊", "星尘Minus", "海伊", "星尘infinity", "诗岸", "KBShinya", "三无Marblue", "奇然liya", "九渊", "牧心"]
作词 = ["白奇", "惊竹娇", "骆栖淮", "冉语优", "司隶示皇", "狐離肯定行", "择荇", "慕清明", "何杏园"]
作曲 = ["Ice-Paper", "林华瑞", "水沐", "litterzy", "陈亦洺", "PokeR", "小可", "酷丘", "周果亦", "潮汐-tide", "沈雾敛"]
编曲 = ["Mzf小慕", "林华瑞", "云宏", "李大白", "周果亦", "崔博源", "1AN孙毅然"]
调校 = ["Creuzer", "坐标P", "瑞安Ryan", "陌生来访"]
曲绘 = ["原生不在", "白夜零BYL", "小狐兔美", "竹竹竹篮子", "狗富贵旺旺旺", "獾有财发发发", "zeii犬间", "Mmmilk_ 忠发财", "橡啊果啊", "忠忠", "披萨仙人", "汪药丸", "丹忱", "竹篮子", "白鄔東", "牧凨", "华胤", "一滩好氰", "梨乖酥", "眠七", "夜电比卡丘", "萧云也", "海豚岛", "杉里沐", "白川柏川", "寒衣", "桃园工作室美术组"]
混音 = ["Mr.曾经", "林华瑞", "周果亦", "周天澈", "泽猫"]