发行日期 = "2025-02-13"
出品 = []
前缀 = ""
中文名 = "依睐·幻想曲"
英文名 = ""
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1WtKpeyEvd)"
购买 = ""
电子 = ""
演唱 = []
作词 = ["陆柒柒", "果汁凉菜", "苏栗无", "纪远", "邪叫教主", "林檎desu", "薇采之依", "举烛", "安陵影钦", "雲夏"]
作曲 = ["闹闹丶", "幻天heart"]
编曲 = ["闹闹丶", "幻天heart"]
调校 = ["FFF君"]
曲绘 = ["Ar極光", "boorain", "利刹牙口", "川泽纡"]
混音 = ["小欧Ω"]
