发行日期 = "2016-07-24"
出品 = ["平行四界Quadimension"]
前缀 = ""
中文名 = "平行四界×轻文轻小说"
英文名 = ""
后缀 = "Vol.1"
歌词制作 = ["神武竹"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Us411v7vG/)"
购买 = "通贩不可用"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["纯白", "雨狸", "某洛", "赭莓奶"]
作曲 = ["纯白", "希望索任合资", "Eurico", "小野道"]
编曲 = ["纯白", "希望索任合资", "乌龟Sui", "小野道"]
调校 = ["纳兰寻风", "小野道"]
曲绘 = ["swd3e2", "骸鸦", "Cotta", "TOMATO"]
混音 = ["希望索任合资", "乌龟Sui", "小野道"]
