发行日期 = "2022-08-12"
出品 = "['奶牛组']"
歌词制作 = "['神武竹']"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1rF411c7ba/)"
购买 = "[淘宝 萌宅幻想](https://e.tb.cn/h.7AUjJwXktXotzR1?tk=6etWUpFgJ95) ￥108"
电子 = "[Dizzylab](https://www.dizzylab.net/d/FuPian/) ￥68"
演唱 = ["星尘minus"]
作词 = ["沈病娇"]
作曲 = ["复响/erazedfx"]
编曲 = ["复响/erazedfx"]
调校 = ["复响/erazedfx"]
曲绘 = ["蛋花花花。"]
混音 = ["复响/erazedfx"]
