发行日期 = "2024-07-18"
出品 = "['胧']"
歌词制作 = "['RQvan']"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Yi421e7bR/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/lnct001/) ￥15"
演唱 = ["星尘", "牧心", "赤羽", "Minus"]
作词 = ["胧", "Aya-亚夜-", "浓缩排骨", "大九_LN"]
作曲 = ["胧", "Aya-亚夜-"]
编曲 = ["胧", "Aya-亚夜"]
调校 = ["Creuzer", "跨海星尘", "瑞安Ryan"]
曲绘 = ["格雷Kun_", "辰暮sora"]
混音 = []
