发行日期 = "2026-05-29"
出品 = []
前缀 = ""
中文名 = "维·爱"
英文名 = "L'amouЯ"
后缀 = ""
歌词制作 = ["jiangchenyu0", "神武竹"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1VTVb6MEDC)"
购买 = ""
电子 = ""
演唱 = ["海伊", "赤羽", "诗岸", "星尘", "苍穹", "BruceMercer2016"]
作词 = []
作曲 = []
编曲 = []
调校 = []
曲绘 = []
混音 = []
