发行日期 = "2026-01-31"
出品 = ["Zeno"]
歌词制作 = ["RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1vz6pBxEqh/)"
购买 = "[淘宝 平行四界Quadimension](https://item.taobao.com/item.htm?id=1019788252972) ￥100/￥150/￥210"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["Zeno"]
作曲 = ["Zeno"]
编曲 = ["Zeno"]
调校 = ["Zeno"]
曲绘 = ["白祈"]
混音 = []
