发行日期 = "2021-08-07"
出品 = "奶牛组"
歌词制作 = "神武竹"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Hq4y1p7qn/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/DessertDiary/) ￥18"
演唱 = ["星尘"]
作词 = ["大九_LN"]
作曲 = ["甜食品鉴委员会 (FX/erazedfx)"]
编曲 = ["甜食品鉴委员会 (FX/erazedfx)"]
调校 = ["甜食品鉴委员会 (FX/erazedfx)"]
曲绘 = ["生吞西瓜x_bz"]
混音 = ["甜食品鉴委员会 (FX/erazedfx)"]
