发行日期 = "2026-05-23"
出品 = ["墨清弦相关收集站"]
前缀 = ""
中文名 = "绮遇"
英文名 = "Pr7sm"
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1sFGh6oET1)"
购买 = ""
电子 = ""
演唱 = ["墨清弦"]
作词 = ["Kindling", "萧暮雨", "浮青雀", "苏栗无", "两色源", "果汁凉菜", "大九", "踊音", "琴南Kodoku"]
作曲 = ["小欧", "枫音", "砖厂浪人", "野良犬", "墨梓", "伊野奏", "FFFFFran", "琴南Kodoku"]
编曲 = []
调校 = ["清茶", "莫米兔", "陌生来访", "哈士奇", "跨海星尘", "Creuzer", "某只泽", "奶油味儿的蘑菇w"]
曲绘 = ["星空lone", "团一", "万点水", "小林", "暮和", "韶华", "soko", "果酱子", "borain"]
混音 = ["小欧", "墨梓", "伊野奏", "中村寧々"]
