发行日期 = "2023-11-25"
出品 = ["Licis"]
前缀 = ""
中文名 = "伊甸园"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1j34y1w7Ye/)"
购买 = ""
电子 = ""
演唱 = ["言和"]
作词 = ["Licis"]
作曲 = ["Licis"]
编曲 = ["Licis"]
调校 = ["白洛 Hoshino", "鬼面 P", "陌生来访", "想吃素的 BeaR"]
曲绘 = ["鸟"]
混音 = []
