"发行日期" = "2018-03-23"
"出品" = ["平行四界Quadimension"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1qW411g7w7/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=686834006107) ￥75"
"电子" = "购买实体版后留电子邮箱地址给淘宝客服索取电子版"
"歌词制作" = ["_IIUFOII_"]
"演唱" = ["星尘", "洛天依", "乐正绫", "言和"]
"作词" = ["Dia", "小明是根草", "冥凰", "雨狸", "绛舞乱丸", "Zeno", "COP"]
"作曲" = ["ANK", "小明是根草", "Ceekyo", "星辉", "绛舞乱丸", "Zeno", "COP"]
"编曲" = ["ANK", "小明是根草", "Ceekyo", "星辉", "绛舞乱丸", "Zeno", "COP"]
"调校" = ["心", "顾令", "冰山", "小明是根草", "Ceekyo", "绛舞乱丸", "Zeno", "COP"]
"曲绘" = ["Muir", "抹茶", "莱勒", "零届0rz", "gods", "咩煲", "诗驯", "唯Tu"]
"混音" = []