"发行日期" = "2022-04-03"
"出品" = ["平行四界Quadimension"]
"前缀" = ""
"中文名" = "平行四界"
"英文名" = "Quadimension"
"后缀" = "X-3"
"歌词制作" = ["虎啸ROAR"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1E5411D7by/)"
"购买" = "[淘宝 平行四界Quadimension](http://t.cn/A66IQrPC) ￥75/￥155/￥185/￥215"
"电子" = "随专辑附赠"
"演唱" = ["星尘", "海伊", "诗岸", "苍穹", "赤羽", "Minus"]
"作词" = ["绿无", "浓缩排骨", "Ddickky", "大♂古", "Zeno", "公兔", "St", "Evalia"]
"作曲" = ["MeLo", "磁带君", "Kide", "Zeno", "胧", "公兔", "PoKeR", "Evalia"]
"编曲" = ["MeLo", "磁带君", "Kide", "Zeno", "胧", "公兔", "PoKeR", "Evalia"]
"调校" = ["瑞安Ryan", "Kide", "坐标P", "Zeno", "顾令", "Creuzer", "陌生来访"]
"曲绘" = ["影依望远镜", "Leiq雷", "Hanasa", "渡五趣", "獾有财发发发", "原子Dan", "大汉Jax", "天白灾", "烧老啾"]
"混音" = []
"母带" = []
"视频" = []
"策划" = []
