"发行日期" = "2019-12-14"
"出品" = ["奶牛组"]
"前缀" = ""
"中文名" = "深潜之宙"
"英文名" = ""
"后缀" = ""
"歌词制作" = ["高冷帝佚名(Polaris_Light)"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1vJ411r7Nz/)"
"购买" = "通贩不可用"
"电子" = "[Dizzylab](https://www.dizzylab.net/d/shenqianzhizhou/) ￥60"
"演唱" = ["苍穹"]
"作词" = ["沈病娇"]
"作曲" = ["Kinoko蘑菇"]
"编曲" = ["Kinoko蘑菇"]
"调校" = ["Kinoko蘑菇", "瑞安Ryan", "木变石"]
"曲绘" = ["星火"]
"混音" = ["Kinoko蘑菇"]
"母带" = []
"视频" = []
"策划" = []
