发行日期 = "2020-12-18"
出品 = "喻川"
歌词制作 = "虎啸ROAR"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1it4y1k7T/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/WriteYouaSong/) ￥30"
演唱 = ["乐正龙牙", "赤羽", "苍穹", "海伊", "Eleanor Forte", "Minus"]
作词 = ["喻川", "逐火", "Vagary", "乾坤"]
作曲 = ["喻川"]
编曲 = ["喻川"]
调校 = ["喻川"]
曲绘 = ["秋燁", "山荷"]
混音 = ["喻川"]
