发行日期 = "2025-08-12"
出品 = "五维介质Official"
歌词制作 = "武乙凌薇"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1uKtSz6EgF/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=991410246698) ￥108/￥178/￥228"
电子 = "随专辑附赠"
演唱 = ["星尘", "赤羽", "海伊", "诗岸", "苍穹"]
作词 = ["黑金语", "林擒", "乌梅Pd", "Zeno", "浓缩排骨", "Aya-亚夜-", "大久"]
作曲 = ["烂兔子P", "乌梅Pd", "Zeno", "胧", "Kide", "Aya-亚夜-", "Bitman"]
编曲 = ["Evalia-爱娃", "烂兔子P", "乌梅Pd", "Zeno", "胧", "Kide", "Aya-亚夜-", "Bitman"]
调校 = ["瑞安Ryan", "跨海星尘", "苍梧 玖蝶"]
曲绘 = ["机器", "碳烤腰关节", "立旗", "尤米妖妖", "匙", "原画-Tiko 修改-匙", "Inoriac"]
混音 = []
