发行日期 = "2026-04-26"
出品 = ["罗绮星雨"]
前缀 = ""
中文名 = "于星海中归于虚无"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1doofBqE2Q)"
购买 = ""
电子 = ""
演唱 = ["星尘"]
作词 = ["雒清辞明"]
作曲 = ["ZClear", "MOCKER44 CTY2p", "花水r"]
编曲 = []
调校 = ["Risho"]
曲绘 = ["Kosaka"]
混音 = []
母带 = []
视频 = []
策划 = []
