发行日期 = "2019-03-29"
出品 = []
前缀 = ""
中文名 = "从众效应"
英文名 = "Conformity"
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Ub411x7LD)"
购买 = ""
电子 = "[Dizzylab](https://www.dizzylab.net/d/Conformity/)"
演唱 = []
作词 = ["绛舞乱丸"]
作曲 = ["绛舞乱丸"]
编曲 = ["绛舞乱丸"]
调校 = ["绛舞乱丸"]
曲绘 = ["阿撸", "苒昀", "叉叉"]
混音 = ["绛舞乱丸"]
