发行日期 = "2020-02-28"
出品 = "五维介质Official"
购买 = "[淘宝 平行四界Quadimension](http://t.cn/A6PVX2ud)"
演唱 = ["星尘", "苍穹", "诗岸"]
作词 = ["Evalia", "哈密瓜", "绿无", "琉璃菌", "Zeno", "赭柚奶", "大九_LN"]
作曲 = ["Evalia", "哈密瓜", "MeLo", "十音", "Zeno", "小野道", "星辉", "磁带君"]
调校 = ["坐标P", "瑞安Ryan", "Zeno", "顾令"]
