发行日期 = "2022-12-31"
出品 = "流星空间站创作组"
歌词制作 = ""
发布 = "[Bilibili](https://www.bilibili.com/video/BV1xA411S7m4/)"
购买 = "[淘宝 靘鱼研究所](https://item.taobao.com/item.htm?id=695728872953) ￥85"
电子 = "[Dizzylab](https://www.dizzylab.net/d/meteory/) ￥67"
演唱 = ["星尘", "永夜Minus", "诗岸", "海伊", "洛天依"]
作词 = ["不鱼"]
作曲 = ["沉林川", "不鱼", "靘"]
编曲 = ["沉林川", "不鱼", "靘"]
调校 = ["不鱼"]
曲绘 = ["不鱼", "莫失迷", "靘", "Tico"]
混音 = ["沉林川"]