发行日期 = "2023-07-06"
出品 = ["靘鱼研究所"]
前缀 = ""
中文名 = "卧室四格"
英文名 = "Mobiusroom"
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV11u4y1r7fC)"
购买 = "[淘宝 靘鱼研究所](https://item.taobao.com/item.htm?id=727522604363) ￥85(通常版)"
电子 = "[dizzylab](https://www.dizzylab.net/d/mobiusroom/)"
演唱 = ["言和"]
作词 = ["雪人Snowman_", "负二价-", "海格P", "萤失Hinano", "Kolaa", "青色靘", "楽素_"]
作曲 = ["雪人Snowman_", "负二价-", "星辉P", "Kolaa", "青色靘", "楽素_"]
编曲 = ["雪人Snowman_", "负二价-", "星辉P", "Kolaa", "青色靘", "楽素_"]
调校 = ["木变石", "负二价-", "Kolaa", "青色靘"]
曲绘 = ["无猫肥宅阿由", "负二价-", "薬屋", "溯鲸", "青色靘", "不鱼"]
混音 = ["雪人Snowman_", "负二价-", "星辉P", "Kolaa", "青色靘", "楽素_"]
母带 = []
视频 = []
策划 = []
