"发行日期" = "2016-11-11"
"出品" = ["平行四界Quadimension"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV16s411x7sf/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=584923080875)"
"电子" = "购买实体版后留电子邮箱地址给淘宝客服索取电子版"
"歌词制作" = ["_IIUFOII_"]
"演唱" = ["洛天依", "乐正绫", "星尘"]
"作词" = ["冥凰", "西洋骨董", "袖蓝", "泓"]
"作曲" = ["小野道", "泓", "大馄饨", "战场原妖精"]
"编曲" = ["小野道", "泓", "大馄饨", "战场原妖精"]
"调校" = []
"曲绘" = ["TOMATO"]
"混音" = []