"发行日期" = "1970-01-01"
"出品" = ["不适用"]
"前缀" = ""
"中文名" = "单曲"
"英文名" = ""
"后缀" = ""
"歌词制作" = ["不适用"]
"发布" = "不适用"
"购买" = "不适用"
"电子" = "不适用"
"演唱" = ["不适用"]
"作词" = ["不适用"]
"作曲" = ["不适用"]
"编曲" = ["不适用"]
"调校" = ["不适用"]
"曲绘" = ["不适用"]
"混音" = ["不适用"]
"母带" = []
"视频" = []
"策划" = []
