发行日期 = "2020-03-20"
出品 = ["我是石榴皮"]
前缀 = ""
中文名 = "塌陷于38°C的蓝"
英文名 = ""
后缀 = ""
歌词制作 = ["RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV19E411J7BL/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/CRASHIN38C/) ￥25"
演唱 = ["星尘", "海伊", "诗岸"]
作词 = ["46"]
作曲 = ["46"]
编曲 = ["46"]
调校 = ["46"]
曲绘 = ["电鱼"]
混音 = ["46"]
