发行日期 = "2020-01-24"
出品 = "['FM40.4']"
歌词制作 = "['RQvan']"
发布 = "[Bilibili](https://www.bilibili.com/video/BV197411a7uT/)"
购买 = "[淘宝 萌宅幻想](https://e.tb.cn/h.iaUF0KqBaI2eTDp?tk=iX9WUpGiid2) ￥60/￥80/￥110"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["3120", "十八", "七月六"]
作曲 = ["烂兔子", "Zeno"]
编曲 = ["烂兔子", "Zeno"]
调校 = ["Creuzer", "烂兔子", "Zeno"]
曲绘 = ["2LH", "tiko", "骸鸭", "疯狐"]
混音 = ["咖啡叔"]
