发行日期 = ""
出品 = []
前缀 = ""
中文名 = "视星等4.44"
英文名 = ""
后缀 = ""
歌词制作 = ["SST"]
发布 = ""
购买 = ""
电子 = ""
演唱 = ["狐狸座Vul", "狐狸座"]
作词 = ["雨狸", "素珏"]
作曲 = ["朝霧坂子", "DELA_P", "可嗒_Keda", "潜移默化♀浅姨磨花", "TeddyAster"]
编曲 = ["胡蝶Dorian", "可嗒_Keda", "ZZM泽貓", "潜移默化♀浅姨磨花"]
调校 = ["Astrodyne", "某FFF的V家粉", "MACHWOLF", "野良犬P", "纤莫"]
曲绘 = ["Lune", "Lune__", "安cle"]
混音 = ["胡蝶Dorian", "潜移默化♀浅姨磨花"]
