发行日期 = "2025-11-24"
出品 = ["闹闹丶", "陆柒柒_Lv77"]
前缀 = ""
中文名 = "南北谐响诗"
英文名 = ""
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1LcSjBhEtW/)"
购买 = ""
电子 = ""
演唱 = ["洛天依", "乐正绫"]
作词 = ["陆柒柒"]
作曲 = ["闹闹丶"]
编曲 = ["闹闹丶"]
调校 = ["苍梧_abilrue", "函数如会函数", "哈士奇 P", "鬼面 P", "磷元素 P"]
曲绘 = ["疯狐", "初凔", "可爱小 x 宝", "甘小宁 R"]
混音 = ["欧 Ohm"]
母带 = []
视频 = []
策划 = []
