发行日期 = "2023-06-23"
出品 = []
前缀 = ""
中文名 = "在人间"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Ej411Q7mz)"
购买 = ""
电子 = ""
演唱 = ["言和"]
作词 = ["瞳荧"]
作曲 = ["烂兔子", "斯大王"]
编曲 = ["烂兔子", "斯大王"]
调校 = ["纳兰寻风"]
曲绘 = ["六两", "SASA"]
混音 = ["沈钰博", "烂兔子"]
