发行日期 = "2026-05-30"
出品 = []
前缀 = ""
中文名 = "溯流"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1v1VM6DE9Q)"
购买 = ""
电子 = ""
演唱 = ["星尘", "海伊", "诗岸"]
作词 = ["雪域小汪", "Yosklex", "霁岚", "琉璃染花灯", "奈奈写满了一整夜", "安斯和洛洛", "熊青嵐", "朝菌", "夜莺叮叮当", "丁小爷p", "零宇"]
作曲 = ["雪域小汪", "Dray", "霁岚", "星晨", "怅梦", "末鸢", "阿昆达", "cco", "熊青嵐", "朝菌", "夜莺叮叮当", "可乐p", "零宇"]
编曲 = []
调校 = ["凛空小猫", "Dray", "阿昆达", "正十字p", "末鸢", "tc", "菜狗_VD", "可乐p", "零宇"]
曲绘 = ["Aries苑"]
混音 = ["霁岚"]
