发行日期 = "2024-08-12"
出品 = ["青蓝", "夜屠灵"]
前缀 = ""
中文名 = "星遇"
英文名 = ""
后缀 = ""
歌词制作 = ["神武竹"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1h3YdeUEcU/)"
购买 = "通贩不可用"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["安筱然", "静听", "水螅", "星语落枫", "江北忆", "亦晗", "珞一"]
作曲 = ["夜屠灵", "大懒", "星语落枫", "ILLUSION-哲", "祈忧", "涅不拉几的"]
编曲 = ["夜屠灵", "大懒", "ILLUSION-哲", "祈忧", "涅不拉几的"]
调校 = ["九雪ICE", "桂月锁心", "某只泽", "跨海星尘", "霜凝玥", "茂名经济黑洞"]
曲绘 = ["是桔子不是橘子的桔子", "GX君", "浅笑", "咲柰", "酒井栗子", "白", "椿色墨魚餅", "林羊", "积雨云"]
混音 = ["唐兰P", "夜屠灵", "虎皮猫", "ILLUSION-哲", "樱庭落", "涅不拉几的"]
