发行日期 = "2021-06-21"
出品 = []
前缀 = ""
中文名 = "见月"
英文名 = "Lunatic"
后缀 = "EP"
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV17X4y1A7nH)"
购买 = ""
电子 = ""
演唱 = []
作词 = []
作曲 = []
编曲 = []
调校 = []
曲绘 = []
混音 = []
母带 = []
视频 = []
策划 = []
