发行日期 = "2025-10-10"
出品 = ["星韵社"]
前缀 = ""
中文名 = "页间曲"
英文名 = ""
后缀 = ""
歌词制作 = ["神武竹"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV14H47zjEin/)"
购买 = "[淘宝 星韵社](https://e.tb.cn/h.R1cvXOGlmABT07g?tk=f2Pd5sNbjUl)"
电子 = "[dizzylab](https://www.dizzylab.net/d/SD-03/)"
演唱 = ["赤羽", "洛天依", "永夜MInus", "星尘", "初音ミク", "闇音レンリ", "诗岸", "乐正绫"]
作词 = ["comdull", "Yuink", "oO杳Oo", "CRS", "纪余珊", "m1rac", "ひかり", "南北百合朝", "Dasein"]
作曲 = ["comdull", "Yuink", "oO杳Oo", "CRS", "m1rac", "_B3nwalker_", "菠萝罐头", "墨绫P", "纪余珊"]
编曲 = ["comdull", "Yuink", "oO杳Oo", "CRS", "m1rac", "_B3nwalker_", "菠萝罐头", "墨绫P", "纪余珊"]
调校 = ["comdull", "Yuink", "oO杳Oo", "CRS", "m1rac", "qwq自动机", "木羲kigiko", "浪隐波风", "墨绫P", "纪余珊"]
曲绘 = ["予澈", "GoNorthMang", "灰域漫游者", "袋子", "lain", "GLanDoSS"]
混音 = ["X-Dimension", "oO杳Oo", "墨绫P"]
母带 = []
视频 = []
策划 = []
