发行日期 = "2019-07-05"
出品 = "五维介质Official"
歌词制作 = ""
发布 = "[Bilibili](https://www.bilibili.com/video/BV1k4411c7Ge/)"
购买 = "[淘宝 平行四界Quadimension](https://item.taobao.com/item.htm?id=992747517068) ￥75/￥120/￥160/￥190"
电子 = "随专辑附赠"
演唱 = ["星尘", "赤羽", "诗岸"]
作词 = ["绿无", "大九_LN", "Uniparity", "赭柚奶", "浓缩排骨", "Kide"]
作曲 = ["Kide", "Melo", "泓", "Hoskey", "小野道", "星辉P", "kide", "Zeno", "战场原妖精"]
编曲 = ["Kide", "Melo", "泓", "Hoskey", "小野道", "星辉P", "kide", "Zeno", "战场原妖精"]
调校 = ["Creuzer", "Melo", "心", "Zeno", "坐标P", "瑞安Ryan", "小野道", "cillia", "Kide", "战场原妖精"]
曲绘 = ["kieed", "匙", "Hanasa", "原子Dan", "TOMATO", "烧饼", "大汉Jax"]
混音 = []
