发行日期 = "2020-03-13"
出品 = ["墨蓝酱油"]
前缀 = ""
中文名 = ""
英文名 = "Cotton Candy"
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1uE411M7ZR/)"
购买 = "[淘宝 DarkBlue Records](https://t.cn/A6zwm3bm) 通贩不可用"
电子 = "[DizzyLab](https://www.dizzylab.net/d/cottoncandy/) ￥20"
演唱 = ["音街ウナ", "星尘", "洛天依", "乐正绫", "海伊"]
作词 = ["墨蓝酱油"]
作曲 = ["墨蓝酱油"]
编曲 = ["墨蓝酱油"]
调校 = ["墨蓝酱油"]
曲绘 = ["RiN", "深谷", "兜兜", "苏以墨", "瑛砸", "发酵末"]
混音 = ["墨蓝酱油"]
母带 = []
视频 = []
策划 = []
