"发行日期" = "2016-06-17"
"出品" = ["平行四界Quadimension"]
"前缀" = ""
"中文名" = "平行四界"
"英文名" = "Quadimension"
"后缀" = "5"
"歌词制作" = ["_IIUFOII_"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1Ss411e7FG/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=686834006107) ￥75"
"电子" = "购买实体版后留电子邮箱地址给淘宝客服索取电子版"
"演唱" = ["洛天依", "乐正绫", "星尘"]
"作词" = ["和田野", "果汁凉菜", "小明是根草", "绛舞乱丸", "陌小幽", "SEVEN", "袖蓝", "绿邪", "Zeno", "Ddickky"]
"作曲" = ["泓", "希望索任合资", "小明是根草", "绛舞乱丸", "St.K4N3", "Ceekyo", "大馄饨", "绿邪", "MeLo", "Zeno", "Ddickky"]
"编曲" = ["泓", "希望索任合资", "小明是根草", "绛舞乱丸", "St.K4N3", "Ceekyo", "大馄饨", "绿邪", "MeLo", "Zeno", "Ddickky"]
"调校" = []
"曲绘" = ["TOMATO", "疯狐", "雨陌", "Muir", "诗驯", "Sainker", "白祈QSR", "匙", "零届0rz", "Achyue", "银古的绿色"]
"混音" = []
"母带" = []
"视频" = []
"策划" = []
