"发行日期" = "2014-04-04"
"出品" = ["平行四界Quadimension"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1as411Z75p/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=686834006107) ￥75"
"电子" = "购买实体版后留电子邮箱地址给淘宝客服索取电子版"
"歌词制作" = ["_IIUFOII_"]
"演唱" = ["洛天依"]
"作词" = ["麦当叔劳劳", "Ddickky", "战场原妖精", "ZOMiG", "沈病娇", "筠箬", "紫寒怜梦", "咲逸十八"]
"作曲" = ["ZOMiG", "Ddickky", "麦当叔劳劳", "战场原妖精"]
"编曲" = ["ZOMiG", "Ddickky", "麦当叔劳劳", "战场原妖精"]
"调校" = []
"曲绘" = ["Gkun", "碳化", "魔鱼", "星鸦", "酥妃"]
"混音" = []