发行日期 = "2026-07-11"
出品 = []
前缀 = ""
中文名 = "再次呼唤我的名字吧"
英文名 = ""
后缀 = ""
歌词制作 = ["武乙凌薇"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1CBATznEKh)"
购买 = ""
电子 = ""
演唱 = ["乐正绫", "洛天依", "GUMI", "言和", "徵羽摩柯", "墨清弦", "乐正龙牙"]
作词 = ["奥莉安夕", "奥莉安多", "奥莉莎"]
作曲 = ["奥莉安夕", "奥莉安多", "奥莉莎"]
编曲 = []
调校 = ["千寒米诺", "卡莱米诺", "月音", "卡莱米"]
曲绘 = ["蒋叶", "扇桑", "水水母母", "brsr", "水木", "ECHO"]
混音 = ["千寒米诺", "卡莱米诺", "卡莱米"]
母带 = []
视频 = []
策划 = []
