发行日期 = "2026-07-11"
出品 = []
前缀 = ""
中文名 = "再次呼唤我的名字吧"
英文名 = ""
后缀 = ""
歌词制作 = ["武乙凌薇"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1FhEx6XEMu/)"
购买 = "[dizzylab](https://www.dizzylab.net/albums/d/trueName/)"
电子 = ""
演唱 = ["诗岸", "乐正绫", "洛天依", "星尘", "海伊", "言和", "心华", "徵羽摩柯", "墨清弦", "乐正龙牙", "GUMI"]
作词 = ["奥莉安多"]
作曲 = ["奥莉安多"]
编曲 = ["奥莉安多"]
调校 = ["卡莱米诺", "月言誩", "K8L44"]
曲绘 = ["落叶brs", "坦桑", "水水母母", "铅冬", "匿名", "艾可"]
混音 = ["卡莱米诺"]
母带 = []
视频 = []
策划 = []
