发行日期 = "2025-05-02"
出品 = ["流星空间站创作组"]
前缀 = "流星空间站"
中文名 = "流星空间站聆星者"
英文名 = ""
后缀 = "II"
歌词制作 = ["神武竹"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1oaVLzXEzg/)"
购买 = "[淘宝 靘鱼研究所](https://item.taobao.com/item.htm?id=918836127417) ￥76"
电子 = "[Dizzylab](https://www.dizzylab.net/d/Starteller/) 尚未开始售卖"
演唱 = ["星尘infinity", "永夜Minus", "诗岸", "言和"]
作词 = ["大九_LN", "沉林川", "雪人Snowman", "靘QING", "不鱼_P", "毛腿猪兔子"]
作曲 = ["星辉_P", "沉林川", "雪人Snowman", "靘QING", "不鱼_P", "樂素-"]
编曲 = ["星辉_P", "沉林川", "雪人Snowman", "靘QING", "不鱼_P", "樂素-"]
调校 = ["某只泽", "沉林川", "靘QING", "不鱼_P"]
曲绘 = ["不鱼", "莫失迷", "白木莱ct", "靘QING"]
混音 = []
