发行日期 = "2020-11-20"
出品 = "寒 Sir"
歌词制作 = ""
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Qt4y1e79S/)"
购买 = "通贩不可用"
电子 = "随专辑附赠"
演唱 = ["苍穹", "赤羽", "海伊", "牧心"]
作词 = ["离南", "QAQ呵呵达", "水螅", "栊枫", "安筱然", "冰心雪蕊", "亦晗", "珞一不高兴"]
作曲 = ["夜屠灵"]
编曲 = ["夜屠灵"]
调校 = ["懿辰", "鬼面P", "白漪风铃", "脉动", "幽灵子", "良良子", "花筝Anly", "佑可猫", "锝是TC德小猪", "久城", "67P"]
曲绘 = ["唐兰", "萱草", "巫烨", "墨石星", "砚曲", "合鸣", "折兰子", "蚀中Tick"]
混音 = ["夜屠灵", "懿辰"]
