发行日期 = ""
出品 = ""
歌词制作 = ""
发布 = ""
购买 = ""
电子 = ""
演唱 = []
作词 = ["大九_LN"]
作曲 = ["曾怡", "星辉p", "Takna", "雪人Snowman", "Yida", "辻原一郎", "十音Molho"]
编曲 = []
调校 = ["瑞安Ryan", "某只泽", "陌生来访", "星辉p"]
曲绘 = ["-Duoer-", "河豚刺身", "九茶混合物", "月见玉子烧", "不鱼", "慧_Sophie"]
混音 = []
