发行日期 = "2026-02-24"
出品 = "被遗忘者的哀伤"
歌词制作 = ""
发布 = "[Bilibili](https://www.bilibili.com/video/BV1yBfUBoEzh/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=1019714314580) ￥52"
电子 = "随专辑附赠"
演唱 = []
作词 = []
作曲 = []
编曲 = []
调校 = []
曲绘 = []
混音 = []
