发行日期 = "2026-02-24"
出品 = ["被遗忘者的哀伤"]
前缀 = ""
中文名 = "九光年宇宙"
英文名 = "Stellar Nine"
后缀 = ""
歌词制作 = ["武乙凌薇", "RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1yBfUBoEzh/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=1019714314580) ￥52 已完售"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["大床山人", "河冰·浮生", "空想纪录", "天野柚AmanoYuzu", "慕容风", "萧家暮雨", "1mol梨花茶", "北山薇", "被遗忘者的哀伤", "星语落枫", "苏栗无"]
作曲 = ["被遗忘者的哀伤", "Aya-亚夜-", "空想纪录", "怀归", "磷元素P", "1mol梨花茶", "星语落枫", "被遗忘者的逝去"]
编曲 = ["清风疾行没有q", "Aya-亚夜-", "空想纪录", "怀归", "磷元素P", "被遗忘者的哀伤", "幻觉", "被遗忘者的逝去"]
调校 = ["Creuzer", "Aya-亚夜-", "血焰玖蝶", "AkazuYi", "陌生来访", "跨海星尘", "磷元素P", "1mol梨花茶", "John_Em", "Risho"]
曲绘 = ["syknot", "字母球捏", "虫合蜊-", "字母贝斯", "ブウユー", "孜然cike", "migu", "余原", "MIGUAG", "アシタ、", "Eid_Shacklebolt", "Ar極光", "劣人_弗洛", "_方白", "山下鸭鸭窝", "云西西西子", "积雨云", "白", "安拆", "Eurekaしお"]
混音 = ["清风疾行没有q", "Aya-亚夜-", "-CuTTleFiSh", "空想纪录", "磷元素P", "1mol梨花茶", "橘子_JZ_", "DJ鱼谷"]
