发行日期 = "2019-12-15"
出品 = "['奶牛组']"
歌词制作 = "['高冷帝佚名(Polaris_Light)']"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1fJ411r7WC/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/ZhiHuangJi/) ￥78"
演唱 = ["星尘", "苍穹", "诗岸"]
作词 = ["沈病娇", "浓缩排骨", "大九_LN", "大♂古"]
作曲 = ["复响/erazedfx"]
编曲 = ["复响/erazedfx"]
调校 = ["瑞安Ryan"]
曲绘 = ["Athgil"]
混音 = ["复响/erazedfx"]
