发行日期 = "2019-04-05"
出品 = "平行四界Quadimension"
歌词制作 = ""
发布 = "[Bilibili](https://www.bilibili.com/video/BV1bb411g7Zq/)"
购买 = "[淘宝 平行四界Quadimension](http://t.cn/EJ1I7tT) ￥75/￥120/￥140/￥180"
电子 = "随专辑附赠"
演唱 = ["星尘", "海伊", "苍穹"]
作词 = ["琉璃君", "浓缩排骨", "绿无", "赭柚奶", "沈病娇", "大♂古", "大九_LN"]
作曲 = ["黄雷基"]
编曲 = ["lbg"]
调校 = ["Zeno", "Napstina", "Melo"]
曲绘 = ["kieed", "November", "Hanasa", "原子Dan", "TOMATO", "Leiq雷", "Sainker", "匙"]
混音 = ["老E"]
