发行日期 = ""
出品 = ""
演唱 = ["星尘", "海伊", "苍穹"]
作词 = ["琉璃君", "浓缩排骨", "绿无", "赭柚奶", "沈病娇", "大♂古", "大九_LN"]
作曲 = ["黄雷基"]
编曲 = ["lbg"]
调校 = ["Zeno", "Napstina", "Melo"]
曲绘 = ["kieed", "November", "Hanasa", "原子Dan", "TOMATO", "Leiq雷", "Sainker", "匙"]
混音 = ["老E"]
歌词制作 = ""
发布 = ""
购买 = ""
电子 = ""
