发行日期 = "2023-05-14"
出品 = []
前缀 = ""
中文名 = "虚拟工程师日志"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Lg4y1V7Et)"
购买 = ""
电子 = ""
演唱 = []
作词 = []
作曲 = []
编曲 = []
调校 = []
曲绘 = []
混音 = []
