发行日期 = "2023-05-14"
出品 = ["Zill"]
前缀 = ""
中文名 = "虚拟工程师日志"
英文名 = "episodes-of-engineers-virtualization"
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Lg4y1V7Et)"
购买 = "通贩不可用"
电子 = "[dizzylab] (https://www.dizzylab.net/d/episodes-of-engineers-virtualization/ https://www.dizzylab.net/d/episodes-of-engineers-virtualization-side-b/) ￥30"
演唱 = ["海伊", "星尘", "夏语遥"]
作词 = ["Zili"]
作曲 = ["Zili"]
编曲 = ["Zili"]
调校 = ["Zili"]
曲绘 = ["前川琳子", "Nebulium__", "小早川塵也", "深海小镇与猫", "巴拉冰", "薬屋", "森地林边"]
混音 = ["Zili"]
母带 = []
视频 = []
策划 = []
