发行日期 = "2023-04-19"
出品 = ["Aya-亚夜-"]
前缀 = ""
中文名 = "加冕日"
英文名 = "CORONATION DAY"
后缀 = ""
歌词制作 = ["Aya-亚夜-"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1bc411H7xN/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/SFA-001/) ￥20"
演唱 = ["赤羽"]
作词 = ["Aya-亚夜-"]
作曲 = ["Aya-亚夜-"]
编曲 = ["Aya-亚夜-"]
调校 = ["Aya-亚夜-"]
曲绘 = ["_QNE"]
混音 = ["Aya-亚夜-"]
母带 = []
视频 = []
策划 = []
