发行日期 = "2024-08-31"
出品 = []
前缀 = ""
中文名 = "天南海北酥"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV17AnfeBEKM)"
购买 = ""
电子 = ""
演唱 = ["洛天依", "乐正绫", "洛天依乐正绫"]
作词 = ["花间有鹿来", "举烛", "北山薇 作曲 : 被遗忘者的哀伤 编曲 : 被遗忘者的哀伤 《红尘寄雪》", "北山薇"]
作曲 = ["闹闹丶", "Orange Soda"]
编曲 = ["闹闹丶", "Orange Soda"]
调校 = ["潜水荷叶", "哈士奇P", "玖蝶鬼面 P"]
曲绘 = ["绫汜鹣芝"]
混音 = ["小欧", "橘子"]
