发行日期 = "2017-01-31"
出品 = "['平行四界Quadimension']"
歌词制作 = "['RQvan']"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1js41187h4/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=583576510108) ￥75/￥120/￥130/￥160"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["Ddickky", "冥凰", "和田野", "浓缩排骨", "绿邪", "琉璃菌", "Zeno"]
作曲 = ["Ddickky", "战场原妖精", "Kide", "桂子油", "MeLo", "小野道", "天钦", "Zeno"]
编曲 = ["小野道", "天钦", "Kide", "战场原妖精", "桂子油", "Zeno", "MeLo"]
调校 = ["小野道", "天钦", "动点", "战场原妖精", "Zeno", "MeLo"]
曲绘 = ["Nine", "RAN", "匙", "零届Orz", "Nineo", "Hanasa", "Jinko_神子", "和茶"]
混音 = ["王冲", "小龙龙"]
