发行日期 = "2023-11-25"
出品 = ["秘宝旅人"]
前缀 = ""
中文名 = "秘宝旅人"
英文名 = ""
后缀 = "I"
歌词制作 = ["RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1ew411P7f3/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/TRTR01/) ￥68"
演唱 = ["苍穹", "星尘Infinity", "海伊", "诗岸", "希罗多德（青溯）", "Minus", "牧心", "赤羽"]
作词 = ["大九_LN"]
作曲 = ["雪人Snowman_", "Yida", "果子Hugo", "磨蹭_platix_zhang", "星辉p", "MooNote"]
编曲 = ["雪人Snowman_", "Yida", "果子Hugo", "星辉p", "磨蹭_platix_zhang", "MooNote"]
调校 = ["瑞安Ryan不跑调", "某只泽", "陌生来访"]
曲绘 = ["-白以慧-", "多尔及利亚", "不鱼P", "Fanghx_D", "宿崎临也", "天马九茶", "阿裕", "---ACR", "错先生S是成大喵", "河豚", "社恐年糕", "阿轨轨轨w", "毛腿猪兔子"]
混音 = []
