发行日期 = "2021-06-04"
出品 = ["平行四界Quadimension"]
前缀 = ""
中文名 = "平行四界"
英文名 = "Quadimension"
后缀 = "X-1"
歌词制作 = ["虎啸ROAR"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1954y1374F/)"
购买 = "[淘宝 平行四界Quadimension](http://t.cn/A6V6Z5gZ) ￥75/￥130/￥200/￥230"
电子 = "随专辑附赠"
演唱 = []
作词 = ["浓缩排骨", "K_Lacid", "大九_LN", "芍杳", "Evalia", "公兔", "Zeno", "绿无"]
作曲 = ["胧", "PoKeR", "磁带君", "ANK", "papaw泡泡", "Evalia", "公兔", "Zeno", "MeLo"]
编曲 = ["胧", "PoKeR", "磁带君", "ANK", "papaw泡泡", "Evalia", "公兔", "Zeno", "MeLo"]
调校 = ["瑞安Ryan", "PoKeR", "坐标P", "Zeno"]
曲绘 = ["大汉Jax", "青梅丨plumw", "KyuriTizu", "Leiq雷", "November", "Hanasa", "影依望远镜", "立旗", "某狐仙", "枫叶"]
混音 = ["弹棉花的GG", "冬子"]
