发行日期 = ""
出品 = "五维介质Official"
歌词制作 = ""
发布 = ""
购买 = ""
电子 = ""
演唱 = ["海伊", "赤羽", "诗岸", "苍穹", "星尘", "Minus", "星尘Infinity"]
作词 = ["Evalia", "溯回", "芍杳", "Zeno", "浓缩排骨", "绿无", "Ddickky"]
作曲 = []
编曲 = []
调校 = ["瑞安Ryan", "陌生来访", "Zeno"]
曲绘 = ["Hanasa", "原子dan", "Leiq雷", "lnoriac", "立旗", "November", "匙"]
混音 = []
