发行日期 = ""
出品 = ""
歌词制作 = "RQvan"
发布 = ""
购买 = ""
电子 = ""
演唱 = ["牧心", "永夜Minus", "星尘", "海伊"]
作词 = ["大♂古"]
作曲 = ["磁带君"]
编曲 = []
调校 = ["瑞安Ryan", "Creuzer", "陌生来访", "一只大水母p", "飙尘_Konoyo"]
曲绘 = ["游野不野"]
混音 = []
