发行日期 = "2025-12-05"
出品 = ["磁带君"]
歌词制作 = ["RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Yk2xBkEEQ/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=1005297360196) ￥119"
电子 = "[Dizzylab](https://www.dizzylab.net/d/ZRJ3443/) ￥80"
演唱 = ["牧心", "永夜Minus", "星尘", "海伊"]
作词 = ["大♂古"]
作曲 = ["磁带君"]
编曲 = ["磁带君"]
调校 = ["瑞安Ryan", "Creuzer", "陌生来访", "一只大水母p", "飙尘_Konoyo"]
曲绘 = ["游野不野"]
混音 = []
