<template>
  <div class="wb" :data-theme="resolvedTheme">
    <section v-if="restoring" class="wb-card">正在恢复登录状态…</section>
    <section v-else-if="!user" class="wb-card">
      <template v-if="mode === 'login'"><h2>登录工作站</h2><form @submit.prevent="login"><label>用户名<input v-model.trim="credentials.name" autocomplete="username" required></label><label>密码<input v-model="credentials.password" type="password" autocomplete="current-password" required></label><button class="wb-btn primary" :disabled="busy">登录</button></form><button v-if="!setup.needsBootstrap" class="wb-link" @click="mode = 'register'">凭邀请码开号</button><button v-if="setup.needsBootstrap" class="wb-link" @click="mode = 'bootstrap'">设置首个管理员</button></template>
      <template v-else-if="mode === 'register'"><h2>凭邀请码开号</h2><form @submit.prevent="register"><label>邀请码<input v-model.trim="registerForm.invite_code" required></label><label>用户名<input v-model.trim="registerForm.name" autocomplete="username" required></label><label>展示名<input v-model.trim="registerForm.display_name" autocomplete="name"></label><label>密码<input v-model="registerForm.password" type="password" autocomplete="new-password" required></label><button class="wb-btn primary" :disabled="busy">创建账户</button></form><button class="wb-link" @click="mode = 'login'">返回登录</button></template>
      <template v-else><h2>设置首个管理员</h2><form @submit.prevent="bootstrap"><label>部署引导口令<input v-model="bootstrapForm.token" type="password" required></label><label>用户名<input v-model.trim="bootstrapForm.name" autocomplete="username" required></label><label>展示名<input v-model.trim="bootstrapForm.display_name" autocomplete="name"></label><label>密码<input v-model="bootstrapForm.password" type="password" autocomplete="new-password" required></label><button class="wb-btn primary" :disabled="busy">创建管理员</button></form><button class="wb-link" @click="mode = 'login'">返回登录</button></template>
      <p v-if="message" class="wb-msg" :class="{ err: failed }" role="status">{{ message }}</p>
    </section>
    <template v-else><p v-if="message" class="wb-msg" :class="{ err: failed }" role="status">{{ message }}</p><Workspace ref="workspace" :user="user" :theme="resolvedTheme" @unauthorized="endSession" @account="openVirtual('account')" @users="openVirtual('users')"><template #account><AccountSettingsView :user="user" :github-configured="setup.githubConfigured" :adapter="auth" @user="updateUser" @unauthorized="endSession" /></template><template #users><WorkspaceUsersView v-if="user.role === 'admin'" :adapter="auth" @unauthorized="endSession" /></template></Workspace><footer class="wb-footer"><span>{{ user.display_name || user.name }} · {{ user.role === 'admin' ? '管理员' : '编辑者' }}</span><label for="wb-theme">主题</label><select id="wb-theme" v-model="themePreference" class="wb-theme-select" aria-label="工作站主题"><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">暗色</option></select><button class="wb-btn" type="button" @click="logout">退出</button></footer></template>
  </div>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import Workspace from './Workspace.vue'; import AccountSettingsView from './AccountSettingsView.vue'; import WorkspaceUsersView from './WorkspaceUsersView.vue'; import { createAuthAdapter } from './authAdapter.js';
const THEME_KEY = 'lrc-workstation-theme'; const auth = createAuthAdapter(); const workspace = ref(null); const user = ref(null); const setup = ref({ needsBootstrap: false, githubConfigured: false }); const restoring = ref(true); const busy = ref(false); const mode = ref('login'); const message = ref(''); const failed = ref(false); const themePreference = ref('system'); const systemDark = ref(false);
const credentials = ref({ name: '', password: '' }); const registerForm = ref({ invite_code: '', name: '', display_name: '', password: '' }); const bootstrapForm = ref({ token: '', name: '', display_name: '', password: '' }); const resolvedTheme = computed(() => themePreference.value === 'system' ? (systemDark.value ? 'dark' : 'light') : themePreference.value);
function report(value = '', isFailed = false) { message.value = value; failed.value = isFailed; } function updateUser(next) { user.value = next; }
async function call(action) { busy.value = true; report(); try { const data = await action(); if (data?.user) user.value = data.user; return data; } catch (error) { report(error.message || '网络错误，请重试', true); return null; } finally { busy.value = false; } }
async function login() { const data = await call(() => auth.login(credentials.value.name, credentials.value.password)); if (data?.user) credentials.value.password = ''; } async function register() { const data = await call(() => auth.register(registerForm.value.invite_code, registerForm.value.name, registerForm.value.password, registerForm.value.display_name)); if (data?.user) registerForm.value.password = ''; } async function bootstrap() { const data = await call(() => auth.bootstrap(bootstrapForm.value.token, bootstrapForm.value.name, bootstrapForm.value.password, bootstrapForm.value.display_name)); if (data?.user) { setup.value.needsBootstrap = false; bootstrapForm.value = { token: '', name: '', display_name: '', password: '' }; } }
function endSession() { user.value = null; mode.value = setup.value.needsBootstrap ? 'bootstrap' : 'login'; report('登录已失效，请重新登录', true); } async function logout() { if (!workspace.value?.canLeave?.()) return; try { await auth.logout(); } catch (error) { report(error.message || '退出失败，请重试', true); return; } user.value = null; mode.value = setup.value.needsBootstrap ? 'bootstrap' : 'login'; report(); } async function openVirtual(view) { if (view === 'users' && user.value?.role !== 'admin') return; await nextTick(); workspace.value?.openVirtualView?.(view); }
function handleGithubResult() { const params = new URLSearchParams(window.location.search); if (!params.has('github')) return; const connected = params.get('github') === 'connected'; report(connected ? 'GitHub 已绑定' : `GitHub 绑定失败：${params.get('reason') || '未知错误'}`, !connected); params.delete('github'); params.delete('reason'); window.history.replaceState({}, '', window.location.pathname + (params.size ? '?' + params.toString() : '') + window.location.hash); if (connected) auth.me().then((data) => { if (data.user) user.value = data.user; }).catch(endSession); }
let media; const onThemeChange = (event) => { systemDark.value = event.matches; }; onMounted(async () => { try { const stored = localStorage.getItem(THEME_KEY); themePreference.value = ['system', 'light', 'dark'].includes(stored) ? stored : 'system'; } catch {} media = window.matchMedia('(prefers-color-scheme: dark)'); systemDark.value = media.matches; media.addEventListener('change', onThemeChange); try { setup.value = await auth.setup(); const data = await auth.me(); user.value = data.user; handleGithubResult(); } catch (error) { if (error.status !== 401) report(error.message || '无法连接认证服务', true); mode.value = setup.value.needsBootstrap ? 'bootstrap' : 'login'; } finally { restoring.value = false; } }); onBeforeUnmount(() => media?.removeEventListener('change', onThemeChange)); watch(themePreference, (value) => { try { localStorage.setItem(THEME_KEY, value); } catch {} });
</script>

<style scoped>
.wb { margin:1.5rem 0; --bg-color:#fff; --text-color:#18181b; --border-color:rgba(0,0,0,.15); color:var(--text-color); }.wb[data-theme='dark'] { --bg-color:#111113; --text-color:#e4e4e7; --border-color:rgba(255,255,255,.2); color-scheme:dark; }.wb-card { display:grid; gap:1rem; max-width:30rem; padding:1.25rem; border:1px solid var(--border-color); background:var(--bg-color); }.wb-card h2 { margin:0; font-size:1rem; letter-spacing:.02em; }.wb-card form { display:grid; gap:.65rem; }.wb-card label { display:grid; gap:.3rem; font-size:.82rem; color:#71717a; }.wb-theme-select,.wb-btn,.wb-card input { padding:.45rem .65rem; border:1px solid var(--border-color); border-radius:2px; color:inherit; background:var(--bg-color); font:inherit; }.wb-btn,.wb-link { cursor:pointer; }.wb-link { justify-self:start; padding:0; border:0; color:inherit; background:transparent; font:inherit; text-decoration:underline; text-underline-offset:3px; }.wb-btn.primary { color:#fff; background:#18181b; border-color:#18181b; }.wb[data-theme='dark'] .wb-btn.primary { color:#0a0a0b; background:#fff; border-color:#fff; }.wb-btn:disabled { opacity:.5; cursor:not-allowed; }.wb-msg { color:#52525b; }.wb-msg.err { color:#dc2626; }.wb-footer { background:var(--bg-color); padding:.55rem .75rem; display:flex; align-items:center; justify-content:flex-end; gap:.5rem; margin-top:.55rem; padding-top:.55rem; border-top:1px solid var(--border-color); font-size:.82rem; }
</style>
