"发行日期" = "2015-07-10"
"出品" = ["平行四界Quadimension"]
"前缀" = ""
"中文名" = "平行四界"
"英文名" = "Quadimension"
"后缀" = "3"
"歌词制作" = ["_IIUFOII_"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1Ts411S7Zd/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=686834006107) ￥75"
"电子" = "购买实体版后留电子邮箱地址给淘宝客服索取电子版"
"演唱" = ["洛天依", "乐正绫", "结月缘"]
"作词" = ["绿邪", "陌小幽", "西洋骨董", "Zeno", "紫寒怜梦", "Ddickky", "かごめP", "和田野", "人形兎", "Li Zong"]
"作曲" = ["ZOMiG", "Ddickky", "Melo", "战场原妖精", "Zeno", "人形兎", "Li Zong", "St.K4N3", "かごめP"]
"编曲" = ["ZOMiG", "Ddickky", "Melo", "战场原妖精", "Zeno", "人形兎", "Li Zong", "St.K4N3", "かごめP"]
"调校" = []
"曲绘" = ["Ran", "おにねこ", "Nineo", "匙", "Rosele", "Lucarios", "缺糖的芝士棒", "银古的绿色", "☆Malachite"]
"混音" = []
"母带" = []
"视频" = []
"策划" = []
