"发行日期" = "2023-03-28"
"出品" = ["潮汐逃逸"]
"前缀" = ""
"中文名" = "透明小说"
"英文名" = ""
"后缀" = ""
"歌词制作" = []
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1Tm4y1r7sM)"
"购买" = ""
"电子" = "[Dizzylab](https://www.dizzylab.net/d/toumingxiaoshuo/) ￥100"
"演唱" = ["诗岸"]
"作词" = ["潮汐逃逸"]
"作曲" = ["潮汐逃逸"]
"编曲" = ["潮汐逃逸"]
"调校" = ["潮汐逃逸"]
"曲绘" = ["潮汐逃逸"]
"混音" = ["潮汐逃逸"]
"母带" = []
"视频" = []
"策划" = []
