发行日期 = "2020-08-12"
出品 = "平行四界Quadimension"
歌词制作 = "西霜月Lune"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1mV411z7fw/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=611203888344) ￥65/￥120"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["绿无"]
作曲 = ["MeLo"]
编曲 = ["MeLo"]
调校 = ["MeLo", "瑞安Ryan]
曲绘 = ["HTNK", "今加", "Sainker", "零届0rz", "千凉子", "匙", "Athgil", "万代", "Leiq雷", "鲨鱼卡sayuki", "枫叶", "靡盬菌"]
混音 = []
