"发行日期" = "2020-08-07"
"出品" = ["糖果工坊CandyFactory"]
"前缀" = ""
"中文名" = ""
"英文名" = "FIND ZERO"
"后缀" = ""
"歌词制作" = ["神武竹", "jiangchenyu0"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1mi4y1u7Wb)"
"购买" = ""
"电子" = ""
"演唱" = ["赤塚優一", "初音ミク", "赤羽", "星尘", "海伊", "诗岸", "苍穹"]
"作词" = ["大九_LN", "戴项圈的立花", "白鸟shiro"]
"作曲" = ["SakuyaH", "立花", "戴项圈的立花", "黑岩Bula_Z"]
"编曲" = ["SAKUYA薯片"]
"调校" = ["立花", "戴项圈的立花"]
"曲绘" = ["revol", "萱草砸成酱", "Bula_Z"]
"混音" = ["Sakuya薯片"]
"母带" = []
"视频" = []
"策划" = []
