"发行日期" = "2018-08-11"
"出品" = ["平行四界Quadimension"]
"前缀" = ""
"中文名" = "星之海"
"英文名" = "StarOcean"
"后缀" = ""
"歌词制作" = ["RQvan"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1cs411T7F5/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=583711155480) ￥75/￥110"
"电子" = "随专辑附赠"
"演唱" = ["星尘", "海伊"]
"作词" = ["大♂古", "浓缩排骨", "袖蓝", "Zeno", "赭莓奶", "冥凰", "绿无"]
"作曲" = ["Kide", "大馄饨", "Zeno", "小野道", "Zoey"]
"编曲" = ["Kide", "大馄饨", "Zeno", "小野道", "Zoey"]
"调校" = ["瑞安Ryan", "小野道", "MeLo", "Napstina"]
"曲绘" = ["Hanasa", "原子Dan", "匙", "莱勒", "Kieed"]
"混音" = ["磁带君"]
"母带" = []
"视频" = []
"策划" = []
