发行日期 = "2017-04-22"
出品 = ["小野道"]
前缀 = ""
中文名 = "蝴蝶旅客"
英文名 = ""
后缀 = ""
歌词制作 = ["RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV13x411U7vS/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=583746947337) ￥65/￥100/￥110"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["和田野", "泠鸢yousa", "冥凰", "赭莓奶", "小野道"]
作曲 = ["小野道"]
编曲 = ["小野道"]
调校 = ["小野道"]
曲绘 = ["TOMATO"]
混音 = ["小野道"]
