"发行日期" = "2025-12-24"
"出品" = ["北极圈ArcticLab"]
"前缀" = ""
"中文名" = "终梦"
"英文名" = "Journeyed on Everdream"
"后缀" = ""
"歌词制作" = ["武乙凌薇"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1q3qZBDE9y)"
"购买" = "[北极圈 Arcticlab](https://item.taobao.com/item.htm?id=1004976437319) ￥82"
"电子" = "[Dizzylab](https://www.dizzylab.net/albums/d/ALCD0101/) ￥28"
"演唱" = ["星尘"]
"作词" = ["铃蓝Suzusnow"]
"作曲" = ["铃蓝Suzusnow"]
"编曲" = ["陆云极", "悬空指针"]
"调校" = ["铃蓝Suzusnow"]
"曲绘" = ["咬流心蛋", "狄拉克海里的X鱼", "DPea9", "苦荞KQ"]
"混音" = ["铃蓝Suzusnow"]
"母带" = []
"视频" = []
"策划" = []
