年份 = "2025-12-05"
出品 = "胧"
发布 = "https://www.bilibili.com/video/BV1Jm2LBbEzi/"
购买 = "![淘宝](https://item.taobao.com/item.htm?id=999122563646)"
演唱 = []
作词 = ["胧", "Aya-亚夜-", "林檎", "阿卡娜"]
作曲 = ["胧", "Aya-亚夜-"]
调校 = ["Creuzer", "血焰玖蝶", "跨海星尘", "瑞安Ryan"]