发行日期 = "2025-12-05"
出品 = ["胧"]
前缀 = ""
中文名 = "不适用"
英文名 = "Starlit Whisper"
后缀 = ""
歌词制作 = ["RQvan", "武乙凌薇"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1Jm2LBbEzi/)"
购买 = "[淘宝 喵之宝库miota](https://item.taobao.com/item.htm?id=999122563646) ￥80/￥199/￥248"
电子 = "[Dizzylab](https://www.dizzylab.net/d/lnct002/) ￥20"
演唱 = ["星尘", "赤羽", "诗岸", "海伊", "苍穹"]
作词 = ["胧", "Aya-亚夜-", "林檎", "阿卡娜"]
作曲 = ["胧", "Aya-亚夜-"]
编曲 = ["胧", "Aya-亚夜"]
调校 = ["Creuzer", "血焰玖蝶", "跨海星尘", "瑞安Ryan"]
曲绘 = ["喵太社"]
混音 = []
