发行日期 = "2019-07-06"
出品 = "忘川风华录"
歌词制作 = ""
发布 = "[Bilibili](https://www.bilibili.com/video/BV1N4411w7jL/)"
购买 = "通贩不可用"
电子 = "电子版不可用"
演唱 = ["洛天依", "乐正绫", "星尘", "心华", "初音ミク"]
作词 = ["择荇", "玄天", "慕清明", "无比", "冉语优"]
作曲 = ["灰原穷", "tide-潮汐", "银临", "litterzy", "悠悠酱", "陈亦洺"]
编曲 = ["Mzf小慕", "PoKeR", "灰原穷", "宏宇", "悠悠酱"]
调校 = ["花儿不哭"]
曲绘 = ["企鹅子", "白川柏川", "花开之所", "白鄔東"]
混音 = ["Mr.曾经"]
