发行日期 = "2026-01-11"
出品 = ["不年轻尘"]
歌词制作 = ["官方特典附赠"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1UF6DBdEoJ/)"
购买 = "[微店 星夜梦Astral](https://weidian.com/item.html?itemID=7632812774) 258￥"
电子 = "随专辑附赠"
演唱 = ["洛天依", "诗岸", "海伊", "永夜", "星尘", "乐正绫", "赤羽"]
作词 = ["果汁凉菜", "Zeno", "Kevinz", "茶花巷", "陆柒柒", "浓缩排骨", "米梅林"]
作曲 = ["LS", "鸽稀拉", "Zeno", "云极", "文安笙", "闹闹", "幻觉", "米梅林"]
编曲 = ["LS", "鸽稀拉", "Zeno", "云极", "文安笙", "闹闹", "幻觉", "米梅林"]
调校 = ["Creuzer", "木变石", "瑞安Ryan", "FFF君", "跨海星尘", "米梅林"]
曲绘 = ["咬流心蛋", "Tico", "匙", "鹣芝", "巫烨", "九道梵音", "Mcircle浮空茜"]
混音 = ["欧Ωhm", "米梅林"]
