"发行日期" = "2024-08-31"
"出品" = ["起开"]
"前缀" = ""
"中文名" = "信风至北"
"英文名" = ""
"后缀" = ""
"歌词制作" = ["SST"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1eaHFeqESY)"
"购买" = ""
"电子" = ""
"演唱" = ["乐正龙牙", "言和"]
"作词" = ["licis", "Bung Kon"]
"作曲" = ["licis", "Adam_K", "Bung Kon"]
"编曲" = []
"调校" = []
"曲绘" = []
"混音" = []
"母带" = []
"视频" = []
"策划" = []
