发行日期 = "2022-02-05"
出品 = []
前缀 = ""
中文名 = ""
英文名 = "NO FOR"
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1oS4y1k7Hs)"
购买 = ""
电子 = ""
演唱 = []
作词 = ["sya", "Sya"]
作曲 = ["sya", "Sya"]
编曲 = ["sya", "Sya"]
调校 = []
曲绘 = []
混音 = ["JUSF周存"]
