发行日期 = ""
出品 = []
歌词制作 = ["MiDiCat"]
发布 = ""
购买 = ""
电子 = ""
演唱 = []
作词 = ["溯回", "Grid格子", "天真圆陆鲨/MiDiCat", "一只爵士猫", "萧家暮雨", "清风疾行"]
作曲 = ["MiDiCat", "清风疾行", "Grid格子"]
编曲 = []
调校 = ["血焰玖蝶", "不朽之言", "Grid格子", "陌生来访", "清风疾行"]
曲绘 = ["Tico", "曦子", "小鱼", "拟态四角咩", "曦子/洛儿", "一树羊羊streep", "晟晞Dawn"]
混音 = []
