发行日期 = "2022-01-01"
出品 = []
前缀 = ""
中文名 = "苍穹之痕：混沌时代"
英文名 = ""
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1hi4y1X7bb)"
购买 = "[淘宝 踏云社](https://item.taobao.com/item.htm?id=665358816397)"
电子 = ""
演唱 = []
作词 = []
作曲 = []
编曲 = []
调校 = []
曲绘 = []
混音 = []
