发行日期 = "2022-01-01"
出品 = ["踏云社"]
前缀 = ""
中文名 = "苍穹之痕：混沌时代"
英文名 = ""
后缀 = ""
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1hi4y1X7bb)"
购买 = "[淘宝 踏云社](https://item.taobao.com/item.htm?id=665358816397)"
电子 = ""
演唱 = ["墨清弦", "星尘", "心华", "乐正绫", "洛天依", "言和", "徵羽摩柯", "乐正龙牙"]
作词 = ["Kevinz", "果汁凉菜", "邪叫教主", "初繁言", "-幻-"]
作曲 = ["Kevinz", "七分音符", "海鲜面", "Social Phobia Synaps", "Saikuro"]
编曲 = []
调校 = ["坐标P", "Creuzer", "Dec 顾令"]
曲绘 = ["蛋花", "脩七", "洋芋", "慧慧火", "琥柯"]
混音 = ["咖啡叔", "七分音符"]
