"发行日期" = "2020-07-27"
"出品" = ["我是石榴皮"]
"前缀" = ""
"中文名" = "月光入侵计划"
"英文名" = ""
"后缀" = ""
"歌词制作" = ["RQvan"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1BC4y1h7Vg/)"
"购买" = "通贩不可用"
"电子" = "[Dizzylab](https://www.dizzylab.net/d/moonattack/) ￥20"
"演唱" = ["诗岸"]
"作词" = ["46"]
"作曲" = ["46"]
"编曲" = ["46"]
"调校" = ["冰镇薄荷苏打水&46"]
"曲绘" = ["电鱼"]
"混音" = ["46"]
"母带" = []
"视频" = []
"策划" = []
