发行日期 = ""
出品 = ""
歌词制作 = ""
发布 = ""
购买 = ""
电子 = ""
演唱 = []
作词 = ["雍雁P", "SaladCup", "Asian Lo-Fi Inc."]
作曲 = ["雍雁P", "SaladCup", "Asian Lo-Fi Inc."]
编曲 = ["雍雁P", "SaladCup", "DIAO P"]
调校 = []
曲绘 = []
混音 = []
