"发行日期" = "2017-08-12"
"出品" = ["平行四界Quadimension"]
"前缀" = ""
"中文名" = "平行四界"
"英文名" = "LIVE TOUR OFFICIAL ALBUM"
"后缀" = ""
"歌词制作" = ["RQvan"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV19x411n7z4/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?abbucket=12&id=583278468666)"
"电子" = "随专辑附赠"
"演唱" = ["星尘"]
"作词" = ["冥凰", "Zeno", "陌小幽", "Ceekyo", "果汁凉菜", "绿无", "Systjcfl", "袖蓝", "意志驼", "紫寒怜梦", "咲逸十八", "便器p", "Seven", "筠箬"]
"作曲" = ["ST.K4N3", "Ceekyo", "COP", "Melo", "小野道", "芹菜猪肉大馄饨", "ZOMiG", "便器p", "Zeno", "Ddickky"]
"编曲" = ["ST.K4N3", "Ceekyo", "COP", "Melo", "小野道", "芹菜猪肉大馄饨", "ZOMiG", "战场原妖精", "便器p", "Zeno", "余果"]
"调校" = ["Ace", "绛舞乱丸"]
"曲绘" = ["TOMATO", "莱勒"]
"混音" = ["Kolaa"]
"母带" = []
"视频" = []
"策划" = []
