发行日期 = "2024-07-25"
出品 = []
前缀 = ""
中文名 = "夏浪派对"
英文名 = ""
后缀 = "2024"
歌词制作 = ["SST"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV17E4m1d754)"
购买 = ""
电子 = ""
演唱 = ["洛天依", "乐正绫", "潋妤"]
作词 = ["饭后AfterDinner", "北山薇", "花间有鹿来", "海格P", "苏栗无", "林墨白citrum", "林墨白"]
作曲 = ["饭后AfterDinner", "怀归", "半只金蓝", "闹闹丶", "Atsuko"]
编曲 = ["饭后AfterDinner", "怀归", "半只金蓝", "闹闹丶", "Atsuko"]
调校 = ["磷元素", "糯米", "星际", "跨海星尘", "苍梧_abilrue", "玖蝶"]
曲绘 = ["-霧見冷水", "白", "syknot/哎唠/匙穆/苍梧_abilrue"]
混音 = ["磷元素", "DJ鱼谷"]
