"发行日期" = "2025-07-04"
"出品" = ["秘宝旅人"]
"前缀" = ""
"中文名" = "秘宝旅人"
"英文名" = "Polaris"
"后缀" = "II"
"歌词制作" = ["RQvan"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1vr3jzUEzN/)"
"购买" = "[淘宝 鲸鱼家](https://item.taobao.com/item.htm?id=947365547978) ￥98/￥208"
"电子" = "[Dizzylab](https://www.dizzylab.net/d/trtr-02/) ￥78"
"演唱" = ["Minus", "小春六花", "ナースロボ＿タイプＴ", "默辰", "星尘", "苍穹", "赤羽", "牧心"]
"作词" = ["大九_LN"]
"作曲" = ["曾怡", "星辉p", "Takna", "雪人Snowman", "Yida", "辻原一郎", "十音Molho"]
"编曲" = ["星辉p", "Takna", "雪人Snowman", "Yida", "辻原一郎", "十音Molho"]
"调校" = ["某只泽", "陌生来访", "瑞安Ryan", "星辉p"]
"曲绘" = ["-Duoer-", "河豚刺身", "九茶混合物", "月见玉子烧", "不鱼", "慧_Sophie", "阿轨轨轨w", "毛腿猪兔子"]
"混音" = []
"母带" = []
"视频" = []
"策划" = []
