发行日期 = "2016-03-04"
出品 = "五维介质Official"
歌词制作 = "Baka632"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1xs411Q78p/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=583724383026) ￥80"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["Ddickky", "和田野", "冰镇甜豆浆", "大る古", "小野道", "孙若曦", "绿邪"]
作曲 = ["ZOMiG", "战场原妖精", "Kide", "Zoey", "MeLo", "小野道", "天钧", "Li Zong"]
编曲 = []
调校 = []
曲绘 = ["Nine", "罒", "零届Orz", "TOMATO", "Dangmill", "swd3e2", "唐不叮", "Nineo"]
混音 = []
