发行日期 = "2016-03-04"
出品 = ["平行四界Quadimension"]
前缀 = ""
中文名 = "星愿"
英文名 = "StarWish"
后缀 = ""
歌词制作 = ["西霜月Lune"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1xs411Q78p/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=583724383026) ￥80"
电子 = "随专辑附赠"
演唱 = ["星尘"]
作词 = ["孙若曦", "大♂古", "小野道", "冰镇甜豆浆", "和田野", "绿邪", "Ddickky"]
作曲 = ["ZOMiG", "战场原妖精", "Li Zong", "小野道", "天钦", "Zoey", "MeLo", "Kide"]
编曲 = ["ZOMiG", "战场原妖精", "Li Zong", "小野道", "天钦", "Zoey", "MeLo", "Kide"]
调校 = ["ZOMiG", "战场原妖精", "动点P", "小野道", "天钦", "Zoey", "MeLo"]
曲绘 = ["匙", "swd3e2", "唐不叮", "Dangmill", "TOMATO", "Nineo", "零届Orz", "Nine"]
混音 = ["小龙龙", "老E", "桂子油"]
母带 = []
视频 = []
策划 = []
