发行日期 = "2026-04-21"
出品 = []
前缀 = ""
中文名 = "每种夏天"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV1scoPBtEat)"
购买 = ""
电子 = ""
演唱 = []
作词 = ["风绕落花愁", "溯回", "半只金蓝"]
作曲 = ["半只金蓝"]
编曲 = ["半只金蓝"]
调校 = ["糯米のミ", "鬼面P", "磷元素P"]
曲绘 = []
混音 = []
