"发行日期" = "2014-04-04"
"出品" = ["平行四界Quadimension"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1sx411W7KR/)"
"购买" = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=583330788344)"
"电子" = ""
"歌词制作" = ["_IIUFOII_"]
"演唱" = ["Mr.Mo", "东京塔子", "三无Marblue", "茶理理", "双笙", "小魂", "排骨教主", "雨洛"]
"作词" = ["Ddickky", "秦楼凤吹", "筠箬", "冰镇甜豆浆", "某洛", "大♂古", "陌小幽", "紫寒怜梦"]
"作曲" = ["ZOMiG", "秦楼凤吹", "Kide", "St.K4N3", "MeLo", "Ddickky", "天钦", "Li Zong"]
"编曲" = ["ZOMiG", "战场原妖精", "秦楼凤吹", "Kide", "St.K4N3", "MeLo", "Ddickky", "天钦", "Li Zong"]
"调校" = []
"曲绘" = ["栗原飴", "床君"]
"混音" = []