发行日期 = "2023-05-24"
出品 = ["平行四界Quadimension"]
前缀 = ""
中文名 = "平行四界"
英文名 = "Quadimension Finale"
后缀 = ""
歌词制作 = ["RQvan"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1JX4y1h76t/)"
购买 = "[淘宝 萌宅幻想](https://item.taobao.com/item.htm?id=991089383317) ￥115/￥190"
电子 = "随专辑附赠"
演唱 = ["海伊", "赤羽", "诗岸", "苍穹", "星尘", "Minus"]
作词 = ["Evalia", "溯回", "芍杳", "Zeno", "浓缩排骨", "绿无", "Ddickky"]
作曲 = ["Evalia", "PoKeR", "papaw泡泡", "Zeno", "Misko", "MeLo", "胧"]
编曲 = ["Evalia", "PoKeR", "papaw泡泡", "Zeno", "Misko", "MeLo", "胧"]
调校 = ["瑞安Ryan", "陌生来访", "Zeno"]
曲绘 = ["Hanasa", "原子dan", "Leiq雷", "lnoriac", "立旗", "November", "匙"]
混音 = ["Zeno"]
母带 = []
视频 = []
策划 = []
