发行日期 = "2025-12-13"
出品 = ["蝴蝶效应_BFx"]
前缀 = ""
中文名 = "秩序之瑕"
英文名 = "Blemishes of the Cosmos"
后缀 = ""
歌词制作 = ["Azure霁岚"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV18LmSBGEbY)"
购买 = ""
电子 = "https://www.dizzylab.net/d/Blemishes-2024】"
演唱 = ["星尘Infinity", "Yuma", "Mai", "诗岸"]
作词 = ["Azure霁岚", "兔子_P"]
作曲 = ["Azure霁岚"]
编曲 = ["Azure霁岚"]
调校 = ["Azure霁岚"]
曲绘 = ["枫临糖"]
混音 = ["Azure霁岚"]
母带 = []
视频 = []
策划 = []
