发行日期 = "2025-12-13"
出品 = []
前缀 = ""
中文名 = "秩序之瑕"
英文名 = ""
后缀 = ""
歌词制作 = []
发布 = "[Bilibili](https://www.bilibili.com/video/BV18LmSBGEbY)"
购买 = ""
电子 = "https://www.dizzylab.net/d/Blemishes-2024】"
演唱 = []
作词 = []
作曲 = []
编曲 = []
调校 = []
曲绘 = []
混音 = []
