发行日期 = "2025-02-14"
出品 = "['TOPKINGCREAM']"
歌词制作 = "['SST']"
发布 = "[Bilibili](https://t.bilibili.com/1036751564199428096?share_source=pc_native)"
购买 = "通贩不可用"
电子 = ""
演唱 = ["星尘"]
作词 = ["TOPKINGCREAM"]
作曲 = ["TOPKINGCREAM"]
编曲 = ["TOPKINGCREAM"]
调校 = ["TOPKINGCREAM"]
曲绘 = ["墨心Nagant"]
混音 = ["Yknsm", "Somefree_", "曲悦"]
