发行日期 = "2021-10-29"
出品 = "五维介质Official"
歌词制作 = "吸尘器"
发布 = "[Bilibili](https://www.bilibili.com/video/BV1RR4y1J7NJ/)"
购买 = "[淘宝 平行四界Quadimension](http://t.cn/A6MxerwL) ￥75/￥120/￥170/￥210"
电子 = "随专辑附赠"
演唱 = ["星尘", "海伊", "诗岸", "苍穹", "赤羽", "minus"]
作词 = ["大九_LM", "K_Lacid", "浓缩排骨", "Evalia", "Zeno"]
作曲 = ["BITMAN", "PoKeR", "星辉P", "papaw泡泡", "胧", "Evalia", "Zeno"]
编曲 = ["BITMAN", "PoKeR", "星辉P", "papaw泡泡", "胧", "Evalia", "Zeno", "Kide"]
调校 = ["瑞安Ryan", "顾令"]
曲绘 = ["大汉Jax", "立旗", "yu-x", "QNZY"]
混音 = []
