发行日期 = "2020-06-12"
出品 = ["平行四界Quadimension"]
歌词制作 = ["初天星_official"]
发布 = "[Bilibili](https://www.bilibili.com/video/BV1BA411v7uJ/)"
购买 = "[淘宝 平行四界Quadimension](http://t.cn/A62s4zQQ) ￥75/￥120/￥140/￥190/￥220"
电子 = "随专辑附赠"
演唱 = ["星尘", "苍穹", "赤羽"]
作词 = ["Evalia", "大九_LN", "浓缩排骨", "Zeno", "绿无", "芍杳", "JUSF周存", "胧", "沈病娇"]
作曲 = ["Evalia", "味素", "磁带君", "Zeno", "MeLo", "papaw泡泡", "JUSF周存", "胧", "Kide"]
编曲 = ["Evalia", "味素", "磁带君", "Zeno", "MeLo", "papaw泡泡", "JUSF周存", "胧", "Kide"]
调校 = ["瑞安Ryan", "木变石", "Creuzer", "MeLo", "JUSF周存", "坐标P", "顾令"]
曲绘 = ["Hanasa", "原子Dan", "大汉Jax", "立旗", "Noir", "KyuriTizu", "November", "匙", "Leiq雷"]
混音 = []
