发行日期 = ""
出品 = ""
演唱 = ["吉光"]
作词 = ["绿无", "沈病娇", "芍杳", "浓缩排骨", "大九_LN"]
作曲 = []
编曲 = []
调校 = ["瑞安Ryan", "Melo", "JUSF周存", "顾令", "Creuzer", "木变石", "坐标P"]
曲绘 = ["Hanasa", "原子Dan", "KyuriTizu", "匙", "November", "立旗", "大汉Jax", "Ncir", "Leiq雷"]
混音 = []
歌词制作 = ""
发布 = ""
购买 = ""
电子 = ""
