发行日期 = ""
出品 = []
前缀 = ""
中文名 = "海客谈"
英文名 = ""
后缀 = ""
歌词制作 = ["SST"]
发布 = ""
购买 = ""
电子 = ""
演唱 = []
作词 = ["邪叫教主", "果汁凉菜", "邪叫"]
作曲 = ["康师傅の海鲜面", "海鲜面"]
编曲 = ["海鲜面", "康师傅の海鲜面", "西门振"]
调校 = ["我才木有", "B^2", "挨批熊", "纳兰寻风"]
曲绘 = []
混音 = ["西门振"]
