"发行日期" = "2023-12-22"
"出品" = ["海鲜面", "邪叫教主"]
"前缀" = ""
"中文名" = "海客谈"
"英文名" = ""
"后缀" = ""
"歌词制作" = ["SST"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1oN4y1x7Cp)"
"购买" = ""
"电子" = ""
"演唱" = ["洛天依", "乐正绫", "言和"]
"作词" = ["邪叫教主", "果汁凉菜", "邪叫"]
"作曲" = ["康师傅の海鲜面", "海鲜面"]
"编曲" = ["海鲜面", "康师傅の海鲜面", "西门振"]
"调校" = ["我才木有", "B^2", "挨批熊", "纳兰寻风"]
"曲绘" = ["吟游诗人小白", "竹籽", "酷拉绵太公", "伯娃", "二手仨", "甜水兔", "舟屿", "海纳", "二两", "杏仁粥"]
"混音" = ["西门振"]
"母带" = []
"视频" = []
"策划" = []
