发行日期 = "2025-09-10"
出品 = "我是石榴皮"
歌词制作 = "RQvan"
发布 = "[Bilibili](https://www.bilibili.com/video/BV12Vbxz6EKH/)"
购买 = "通贩不可用"
电子 = "[Dizzylab](https://www.dizzylab.net/d/PixelWasteland/) ￥30"
演唱 = ["诗岸", "星尘", "永夜Minus", "洛天依"]
作词 = ["我是石榴皮"]
作曲 = ["我是石榴皮"]
编曲 = ["我是石榴皮"]
调校 = ["我是石榴皮", "\\\"阿凛子君"]
曲绘 = []
混音 = ["我是石榴皮"]
