"发行日期" = "2024-10-02"
"出品" = ["Sodatune"]
"前缀" = ""
"中文名" = "再见，碳酸海"
"英文名" = ""
"后缀" = "Deluxe"
"歌词制作" = ["RQvan"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV12x4TepELv)"
"购买" = ""
"电子" = "https://www.dizzylab.net/d/ST-007/"
"演唱" = ["洛天依", "乐正绫", "洛天依/乐正绫"]
"作词" = ["举烛", "Soda纯白", "偏生梓归_", "籽树/举烛"]
"作曲" = ["纯白P", "Soda纯白"]
"编曲" = ["DBRT", "Soda纯白", "纯白P"]
"调校" = ["无形歌无形", "纯白P"]
"曲绘" = ["盐"]
"混音" = ["Irecorder", "纯白P"]
"母带" = []
"视频" = []
"策划" = []
