"发行日期" = "2025-12-06"
"出品" = ["喻川YuChuan"]
"前缀" = ""
"中文名" = "假说"
"英文名" = "Hypothesis"
"后缀" = ""
"歌词制作" = ["SST"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1KW2XB6EaG)"
"购买" = ""
"电子" = "[Dizzylab](https://www.dizzylab.net/d/hypothesis/)"
"演唱" = ["默辰", "岸晓"]
"作词" = ["大九_LN", "喻川", "苍梧_abilrue"]
"作曲" = ["喻川"]
"编曲" = ["喻川"]
"调校" = ["瑞安Ryan", "Creuzer", "苍梧_abilrue"]
"曲绘" = ["北鱼", "煤油狸猫", "鲸井", "阿裕"]
"混音" = ["喻川", "Creuzer"]
"母带" = []
"视频" = []
"策划" = []
