发行日期 = ""
出品 = []
前缀 = ""
中文名 = "假说"
英文名 = "Hypothesis"
后缀 = ""
歌词制作 = ["SST"]
发布 = ""
购买 = ""
电子 = "[Dizzylab](https://www.dizzylab.net/d/hypothesis/)"
演唱 = []
作词 = ["大九_LN", "大九_ LN", "喻川", "苍梧_abilrue"]
作曲 = ["喻川"]
编曲 = ["喻川"]
调校 = []
曲绘 = ["北鱼/煤油狸猫", "鲸井", "阿裕/煤油狸猫"]
混音 = ["喻川", "Creuzer"]
